### ISSUE TITLE
showPagingAction not working in Sympfony 2.3

### ISSUE THREAD

**Issue by penfold45** [liip/LiipSearchBundle#10]
Hi

I just upgraded to Symfony 2.3 and appear to have an issue with pagination.

The parameters that get passed to the Pager object no longer appear to exist in $request->query but in $request->attributes.

    public function showPagingAction(Request $request)
    {
        $paging = $this->pager->paging(
            $request->query->get('estimated'),
            $request->query->get('start'),
            $request->query->get('perPage'),
            $request->query->get('query')
        );
        return new Response($this->templating->render('LiipSearchBundle:Search:paging.html.twig',
            array(
                'paging' => $paging,
                'estimated' => $request->query->get('estimated'),
                'translationDomain' => $request->query->get('translationDomain'),
            )));
    }

**Comment by dbu** [comment]
version 2 will use a twig function for the search box and does the pager with pagerfanta. this is a complete BC break for existing templates, but will be a lot more elegant to use.
